import { describe, it, expect } from 'vitest';
import {
  parseClaimFromIssue,
  parseLogMetadata,
  computeTokenSpendFromLogs,
  queryRepoFleetStatus,
  summarizeFleet,
} from '../src/lib/fleet-query.js';

describe('Fleet Query Engine', () => {
  it('parses active and stale claims from issue comments', () => {
    const now = new Date('2026-08-24T12:00:00Z').getTime();

    // 1. Fresh claim (1 hour ago)
    const freshIssue = {
      number: 10,
      title: 'feat: new feature',
      assignees: [{ login: 'agent-bot' }],
      url: 'https://github.com/owner/repo/issues/10',
      comments: [
        {
          body: '🔒 Claimed by autowork run 2026-08-24T11:00:00Z\n\n_Generated by Antigravity_',
          createdAt: '2026-08-24T11:00:00Z',
          author: { login: 'agent-bot' },
        },
      ],
    };

    const freshClaim = parseClaimFromIssue(freshIssue, [], now);
    expect(freshClaim).not.toBeNull();
    expect(freshClaim?.issueNumber).toBe(10);
    expect(freshClaim?.assignee).toBe('agent-bot');
    expect(freshClaim?.ageHours).toBeCloseTo(1.0, 1);
    expect(freshClaim?.isStale).toBe(false);

    // 2. Stale claim (8 hours ago, no open PR)
    const staleIssue = {
      number: 12,
      title: 'fix: broken auth',
      assignees: [{ login: 'agent-bot' }],
      url: 'https://github.com/owner/repo/issues/12',
      comments: [
        {
          body: '🔒 Claimed by autowork run 2026-08-24T04:00:00Z',
          createdAt: '2026-08-24T04:00:00Z',
          author: { login: 'agent-bot' },
        },
      ],
    };

    const staleClaim = parseClaimFromIssue(staleIssue, [], now);
    expect(staleClaim).not.toBeNull();
    expect(staleClaim?.isStale).toBe(true);
    expect(staleClaim?.ageHours).toBeCloseTo(8.0, 1);

    // 3. Old claim but has open PR (not stale per ORCHESTRATION.md)
    const openPRs = [
      {
        number: 105,
        title: 'fix: broken auth',
        body: 'Closes #12',
        headRefName: 'fix/auth',
        author: { login: 'agent-bot' },
        isDraft: false,
        createdAt: '2026-08-24T05:00:00Z',
        updatedAt: '2026-08-24T06:00:00Z',
      },
    ];
    const oldClaimWithPR = parseClaimFromIssue(staleIssue, openPRs, now);
    expect(oldClaimWithPR).not.toBeNull();
    expect(oldClaimWithPR?.isStale).toBe(false);

    // 4. Manual assignment without lock comment is not an autowork claim
    const manualIssue = {
      number: 15,
      title: 'docs: manual work',
      assignees: [{ login: 'human' }],
      comments: [],
    };
    expect(parseClaimFromIssue(manualIssue, [], now)).toBeNull();
  });

  it('parses markdown log metadata tables and computes rolling token spend', () => {
    const log1 = `
# Run Log
## Metadata
| Field | Value |
|-------|-------|
| Routine | \`autowork\` |
| Timestamp | \`2026-08-23T10:00:00Z\` |
| Result | \`SUCCESS\` |
| Input tokens | \`100000\` |
| Output tokens | \`5000\` |
| Estimated cost | \`$1.25\` |
| Duration | \`500s\` |
`;

    const log2 = `
# Run Log
## Metadata
| Field | Value |
|-------|-------|
| Routine | \`peer-review\` |
| Timestamp | \`2026-08-22T08:00:00Z\` |
| Result | \`SUCCESS\` |
| Input tokens | 50000 |
| Output tokens | 2500 |
| Estimated cost | $0.65 |
`;

    // Older than 7 days from now (2026-08-24)
    const oldLog = `
# Run Log
## Metadata
| Field | Value |
|-------|-------|
| Routine | \`autowork\` |
| Timestamp | \`2026-08-10T00:00:00Z\` |
| Result | \`SUCCESS\` |
| Input tokens | 200000 |
| Output tokens | 10000 |
| Estimated cost | $2.50 |
`;

    const meta1 = parseLogMetadata(log1);
    expect(meta1).toEqual({
      routine: 'autowork',
      timestamp: '2026-08-23T10:00:00Z',
      result: 'SUCCESS',
      inputTokens: 100000,
      outputTokens: 5000,
      estimatedCost: 1.25,
      duration: 500,
    });

    const now = new Date('2026-08-24T12:00:00Z').getTime();
    const spend = computeTokenSpendFromLogs([log1, log2, oldLog], now);

    expect(spend.recentRunCount).toBe(2);
    expect(spend.sevenDayInputTokens).toBe(150000);
    expect(spend.sevenDayOutputTokens).toBe(7500);
    expect(spend.sevenDayTotalTokens).toBe(157500);
    expect(spend.sevenDayEstimatedCost).toBeCloseTo(1.90, 2);
  });

  it('queries repo status with mock executor', async () => {
    const mockExecutor = async (args: string[]) => {
      const command = args.join(' ');
      if (command.includes('pr list')) {
        return JSON.stringify([
          {
            number: 42,
            title: 'feat: add metrics',
            author: { login: 'agent' },
            isDraft: false,
            reviewDecision: 'APPROVED',
            createdAt: '2026-08-24T10:00:00Z',
            updatedAt: '2026-08-24T11:00:00Z',
            url: 'https://github.com/owner/repo/pull/42',
            headRefName: 'feat/metrics',
            body: 'Closes #7',
          },
        ]);
      }
      if (command.includes('issue list')) {
        return JSON.stringify([
          {
            number: 7,
            title: 'feat: metrics tracking',
            assignees: [{ login: 'agent' }],
            url: 'https://github.com/owner/repo/issues/7',
            comments: [
              {
                body: '🔒 Claimed by autowork run 2026-08-24T09:00:00Z',
                createdAt: '2026-08-24T09:00:00Z',
                author: { login: 'agent' },
              },
            ],
          },
        ]);
      }
      if (command.includes('api repos/owner/repo/contents/agents-manifest.json')) {
        return JSON.stringify({
          content: Buffer.from(JSON.stringify({ version: '1.0.0', preset: 'standard' })).toString('base64'),
        });
      }
      return '[]';
    };

    const status = await queryRepoFleetStatus('owner/repo', mockExecutor, new Date('2026-08-24T12:00:00Z').getTime());
    expect(status.repo).toBe('owner/repo');
    expect(status.fleetVersion).toBe('1.0.0');
    expect(status.preset).toBe('standard');
    expect(status.openPRs.length).toBe(1);
    expect(status.openPRs[0].number).toBe(42);
    expect(status.openPRs[0].isDraft).toBe(false);
    expect(status.activeClaims.length).toBe(1);
    expect(status.activeClaims[0].issueNumber).toBe(7);
    expect(status.activeClaims[0].isStale).toBe(false);
  });

  it('aggregates fleet summary across multiple repositories', () => {
    const statuses = [
      {
        repo: 'owner/repo-1',
        fleetVersion: '1.0.0',
        preset: 'standard',
        activeClaims: [
          { issueNumber: 1, title: 'a', assignee: 'bot', claimedAt: '...', ageHours: 2, isStale: false },
        ],
        openPRs: [
          { number: 10, title: 'pr1', author: 'bot', isDraft: true, createdAt: '...', updatedAt: '...' },
          { number: 11, title: 'pr2', author: 'bot', isDraft: false, reviewDecision: 'APPROVED', createdAt: '...', updatedAt: '...' },
        ],
        tokenUsage: {
          sevenDayInputTokens: 100000,
          sevenDayOutputTokens: 5000,
          sevenDayTotalTokens: 105000,
          sevenDayEstimatedCost: 1.20,
          recentRunCount: 2,
        },
        staleWarnings: [],
      },
      {
        repo: 'owner/repo-2',
        fleetVersion: '1.0.0',
        preset: 'full',
        activeClaims: [
          { issueNumber: 5, title: 'stale task', assignee: 'bot', claimedAt: '...', ageHours: 9, isStale: true },
        ],
        openPRs: [],
        tokenUsage: {
          sevenDayInputTokens: 50000,
          sevenDayOutputTokens: 2000,
          sevenDayTotalTokens: 52000,
          sevenDayEstimatedCost: 0.60,
          recentRunCount: 1,
        },
        staleWarnings: ['Stale claim on #5'],
      },
    ];

    const summary = summarizeFleet(statuses);
    expect(summary.totalRepos).toBe(2);
    expect(summary.activeClaimsCount).toBe(2);
    expect(summary.staleClaimsCount).toBe(1);
    expect(summary.openPRsCount).toBe(2);
    expect(summary.draftPRsCount).toBe(1);
    expect(summary.readyPRsCount).toBe(1);
    expect(summary.totalTokens7d).toBe(157000);
    expect(summary.totalEstimatedCost7d).toBeCloseTo(1.80, 2);
    expect(summary.totalRuns7d).toBe(3);
  });

  it('computes detailed per-routine token and iteration stats alongside fleet totals', () => {
    const logAutowork1 = `
# Run Log
## Metadata
| Field | Value |
|-------|-------|
| Routine | \`autowork\` |
| Timestamp | \`2026-08-25T01:00:00Z\` |
| Result | \`SUCCESS\` |
| Input tokens | \`80000\` |
| Output tokens | \`5000\` |
| Estimated cost | \`$0.25\` |
| Iterations used | \`20 / 65\` |
| Duration | \`240s\` |
`;

    const logAutowork2 = `
# Run Log
## Metadata
| Field | Value |
|-------|-------|
| Routine | \`autowork\` |
| Timestamp | \`2026-08-25T07:00:00Z\` |
| Result | \`SUCCESS\` |
| Input tokens | \`120000\` |
| Output tokens | \`10000\` |
| Estimated cost | \`$0.40\` |
| Iterations used | \`30 / 65\` |
| Duration | \`360s\` |
`;

    const logReview = `
# Run Log
## Metadata
| Field | Value |
|-------|-------|
| Routine | \`peer-review\` |
| Timestamp | \`2026-08-25T08:00:00Z\` |
| Result | \`SUCCESS\` |
| Input tokens | \`45000\` |
| Output tokens | \`5000\` |
| Estimated cost | \`$0.15\` |
| Iterations used | \`10 / 30\` |
| Duration | \`120s\` |
`;

    const now = new Date('2026-08-25T12:00:00Z').getTime();
    const spend = computeTokenSpendFromLogs([logAutowork1, logAutowork2, logReview], now);

    expect(spend.recentRunCount).toBe(3);
    expect(spend.sevenDayInputTokens).toBe(245000);
    expect(spend.sevenDayOutputTokens).toBe(20000);
    expect(spend.sevenDayTotalTokens).toBe(265000);
    expect(spend.sevenDayEstimatedCost).toBeCloseTo(0.80, 2);

    expect(spend.byRoutine).toBeDefined();
    expect(Object.keys(spend.byRoutine)).toEqual(['autowork', 'peer-review']);

    // Autowork routine breakdown
    const autowork = spend.byRoutine.autowork;
    expect(autowork).toBeDefined();
    expect(autowork.routine).toBe('autowork');
    expect(autowork.runCount).toBe(2);
    expect(autowork.inputTokens).toBe(200000);
    expect(autowork.outputTokens).toBe(15000);
    expect(autowork.totalTokens).toBe(215000);
    expect(autowork.estimatedCost).toBeCloseTo(0.65, 2);
    expect(autowork.avgTokensPerRun).toBe(107500); // 215000 / 2
    expect(autowork.maxTokensPerRun).toBe(130000); // 120000 + 10000
    expect(autowork.avgIterationsUsed).toBe(25.0); // (20 + 30) / 2
    expect(autowork.fleetSharePercent).toBeCloseTo(81.13, 2); // 215000 / 265000 * 100

    // Peer Review routine breakdown
    const peerReview = spend.byRoutine['peer-review'];
    expect(peerReview).toBeDefined();
    expect(peerReview.routine).toBe('peer-review');
    expect(peerReview.runCount).toBe(1);
    expect(peerReview.inputTokens).toBe(45000);
    expect(peerReview.outputTokens).toBe(5000);
    expect(peerReview.totalTokens).toBe(50000);
    expect(peerReview.estimatedCost).toBeCloseTo(0.15, 2);
    expect(peerReview.avgTokensPerRun).toBe(50000);
    expect(peerReview.maxTokensPerRun).toBe(50000);
    expect(peerReview.avgIterationsUsed).toBe(10.0);
    expect(peerReview.fleetSharePercent).toBeCloseTo(18.87, 2); // 50000 / 265000 * 100
  });

  it('handles edge cases in per-routine log parsing (missing routine, malformed numbers, zero runs)', () => {
    const logMissingRoutine = `
# Run Log
## Metadata
| Field | Value |
|-------|-------|
| Timestamp | \`2026-08-25T01:00:00Z\` |
| Result | \`SUCCESS\` |
| Input tokens | \`50000\` |
| Output tokens | \`2000\` |
| Estimated cost | \`$0.12\` |
`;

    const logMalformed = `
# Run Log
## Metadata
| Field | Value |
|-------|-------|
| Routine | \`issues-housekeeping\` |
| Timestamp | \`2026-08-25T02:00:00Z\` |
| Result | \`SUCCESS\` |
| Input tokens | \`N/A\` |
| Output tokens | \`--\` |
| Estimated cost | \`unknown\` |
| Iterations used | \`invalid\` |
`;

    const now = new Date('2026-08-25T12:00:00Z').getTime();
    const spend = computeTokenSpendFromLogs([logMissingRoutine, logMalformed], now);

    expect(spend.recentRunCount).toBe(2);
    expect(spend.byRoutine.unknown).toBeDefined();
    expect(spend.byRoutine.unknown.runCount).toBe(1);
    expect(spend.byRoutine.unknown.inputTokens).toBe(50000);
    expect(spend.byRoutine.unknown.outputTokens).toBe(2000);
    expect(spend.byRoutine.unknown.totalTokens).toBe(52000);
    expect(spend.byRoutine.unknown.avgIterationsUsed).toBeUndefined();
    expect(spend.byRoutine.unknown.fleetSharePercent).toBe(100);

    expect(spend.byRoutine['issues-housekeeping']).toBeDefined();
    expect(spend.byRoutine['issues-housekeeping'].runCount).toBe(1);
    expect(spend.byRoutine['issues-housekeeping'].inputTokens).toBe(0);
    expect(spend.byRoutine['issues-housekeeping'].outputTokens).toBe(0);
    expect(spend.byRoutine['issues-housekeeping'].totalTokens).toBe(0);
    expect(spend.byRoutine['issues-housekeeping'].avgTokensPerRun).toBe(0);
    expect(spend.byRoutine['issues-housekeeping'].maxTokensPerRun).toBe(0);
    expect(spend.byRoutine['issues-housekeeping'].avgIterationsUsed).toBeUndefined();
    expect(spend.byRoutine['issues-housekeeping'].fleetSharePercent).toBe(0);

    // Empty logs test
    const emptySpend = computeTokenSpendFromLogs([], now);
    expect(emptySpend.recentRunCount).toBe(0);
    expect(emptySpend.sevenDayTotalTokens).toBe(0);
    expect(emptySpend.byRoutine).toEqual({});
  });
});
